server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myDatabase
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'

#缓存过期时间
cacheexpire:
  captcha: 100
  account: 3600
  order: 36000

#机器位置
counter:
  #柜台ID
  id: 1000
  #机房ID
  dataCenterId: 0
  #机柜ID
  workerId: 0